### ISSUE TITLE
not allowed to write to `config` object after the trailpack `configure` stage is completed

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trailpack-express4#11]
Modifying config here: https://github.com/trailsjs/trailpack-express4/blob/master/lib/server.js#L48

I added a requirement in the Trailpack spec that the application cannot alter its own configuration after the `configure` lifecycle stage is completed. This is to ensure that the configuration of the application always remains consistent with the initial conditions given to it. 

Test output is here: https://travis-ci.org/trailsjs/trails/jobs/124324336#L781

I also updated the README to be clearer: https://github.com/trailsjs/trailpack/blob/master/README.md#configure-1

**Comment by jaumard** [comment]
Ok I'm looking this

**Comment by jaumard** [comment]
Now Trails tests are successful, so I think it's good for this issue :) let me know if it's not the case.
